Traceback (most recent call last):
  File "C:\Users\admin\OneDrive\Desktop\ForestObservatoryOntology\myenv\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\admin\OneDrive\Desktop\ForestObservatoryOntology\myenv\lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\admin\OneDrive\Desktop\ForestObservatoryOntology\myenv\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\admin\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\admin\OneDrive\Desktop\ForestObservatoryOntology\myenv\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\admin\OneDrive\Desktop\ForestObservatoryOntology\myenv\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\admin\OneDrive\Desktop\ForestObservatoryOntology\myenv\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd #for handling csv and csv contents
from rdflib import Graph, Literal, RDF, URIRef, Namespace #basic RDF handling
from rdflib.namespace import FOAF , XSD, SSN, SOSA #most common namespaces
import urllib.parse #for parsing strings to URI's
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
import stardog
import json
import io
import os
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 1[0m
[1;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m [38;5;66;03m#for handling csv and csv contents[39;00m
[0;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mrdflib[39;00m [38;5;28;01mimport[39;00m Graph, Literal, RDF, URIRef, Namespace [38;5;66;03m#basic RDF handling[39;00m
[0;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mrdflib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mnamespace[39;00m [38;5;28;01mimport[39;00m FOAF , XSD, SSN, SOSA [38;5;66;03m#most common namespaces[39;00m

[1;31mModuleNotFoundError[0m: No module named 'pandas'

